server:
  port:
    8082
spring:
  application:
    name: demo_dmt
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      username: root
      password: example
      authentication-database: admin
