server:
  port:
    8082
spring:
  application:
    name: demo_dmt
  data:
    mongodb:
      uri: mongodb://test-sdba:oMe4kYU8fawDpESmnopc0F85DeuzDfpcnjczJItGTK8QDoi8BJwMav9K6VYIUt1lRO7GXXu21rQ5ACDbalIZdA==@test-sdba.mongo.cosmos.azure.com:10255/test-cdb?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@test-sdba@
