INSERT INTO WAREHOUSES (ID, CLIENT, FAMILY, SIZE, UUID) VALUES (NEXT VALUE FOR WAREHOUSES_SEQ, 'ACME', 0, 100, RANDOM_UUID());

INSERT INTO RACKS (ID, TYPE, WAREHOUSE_ID, UUID) VALUES (NEXT VALUE FOR RACKS_SEQ, 1, CURRENT VALUE FOR WAREHOUSES_SEQ, RANDOM_UUID());

INSERT INTO RACKS (ID, TYPE, WAREHOUSE_ID, UUID) VALUES (NEXT VALUE FOR RACKS_SEQ, 2, CURRENT VALUE FOR WAREHOUSES_SEQ, RANDOM_UUID());

INSERT INTO RACKS (ID, TYPE, WAREHOUSE_ID, UUID) VALUES (NEXT VALUE FOR RACKS_SEQ, 0, CURRENT VALUE FOR WAREHOUSES_SEQ, RANDOM_UUID());